import { BottomBar, Editable, Slide } from '@deckio/deck-engine'
import styles from './ContentSlide.module.css'

export default function ValidationSlide({ index }) {
  return (
    <Slide index={index} className={styles.slide}>
      <div className="accent-bar" />
      <div className="content-frame content-gutter">
        <div className={styles.shell}>
          <div className={styles.brandLine}>
            <span className={styles.microsoftMark} aria-hidden="true">
              <span /><span /><span /><span />
            </span>
            <Editable as="span" id="validate.eyebrow">Validation</Editable>
          </div>

          <Editable as="h2" id="validate.title" className={styles.title}>
            Byte-identical aggregates across all three locations
          </Editable>

          <Editable as="p" id="validate.lede" multiline className={styles.lede}>
            The validator queries the source DW, the Fabric Warehouse, and the Fabric
            Lakehouse, then compares row counts and decimal sums. It passes when counts
            match exactly and sums agree within ±0.01 — at demo scale, all three match
            byte-for-byte, no rounding tolerance required.
          </Editable>

          <table className={styles.table}>
            <thead>
              <tr>
                <th>Table</th>
                <th>Source DW</th>
                <th>Fabric Warehouse</th>
                <th>Fabric Lakehouse</th>
                <th>Aggregate</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td><strong>DimCustomer</strong></td>
                <td>500</td>
                <td>500 ✅</td>
                <td>500 ✅</td>
                <td>20 distinct countries</td>
              </tr>
              <tr>
                <td><strong>DimProduct</strong></td>
                <td>100</td>
                <td>100 ✅</td>
                <td>100 ✅</td>
                <td>SUM(Price) = $23,199.50</td>
              </tr>
              <tr>
                <td><strong>FactOrders</strong></td>
                <td>2,000</td>
                <td>2,000 ✅</td>
                <td>2,000 ✅</td>
                <td>SUM(TotalAmount) = $2,039,990.00</td>
              </tr>
            </tbody>
          </table>

          <ul className={styles.list}>
            <li><strong>Natural keys line up exactly</strong> across all three engines.</li>
            <li><strong>Surrogate keys intentionally excluded</strong> from the parity check — each engine assigns its own.</li>
            <li><strong>Full report</strong> in <span className={styles.code}>tests/validation-report.md</span>, generated by <span className={styles.code}>tests/validate.py</span>.</li>
          </ul>
        </div>
      </div>
      <BottomBar text={<Editable as="span" id="validate.footer">Same numbers. Source DW · Fabric Warehouse · Fabric Lakehouse.</Editable>} />
    </Slide>
  )
}
